name: CI Build Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: emulator

    - name: Clean repo of artifacts
      run: |
        git clean -f

    - name: Cache tup build dependency
      id: cache-tup
      uses: actions/cache@v1
      with:
        path: dependencies/gittup
        key: ${{ runner.OS }}-gittup

    - name: Install tup build dependency
      if: steps.cache-tup.outputs.cache-hit != 'true'
      run: |
        sudo apt install libfuse-dev
        cd "${HOME}"
        git clone https://github.com/gittup/tup.git dependencies/gittup
        cd dependencies/gittup
        ./build.sh
        ./bootstrap.sh
        mkdir -p "${GITHUB_WORKSPACE}/dependencies/gittup"
        cp "${HOME}/dependencies/gittup/build/tup" "${GITHUB_WORKSPACE}/dependencies/gittup/"

    - name: Install gmp library
      run: sudo apt-get install libgmp-dev

    - name: Run a build
      run: |
        "${GITHUB_WORKSPACE}/dependencies/gittup/tup" init
        "${GITHUB_WORKSPACE}/dependencies/gittup/tup"
